---
etcd_vers: etcd-2.3.7
etcd_peer_port: 2380
etcd_peer_url_scheme: http
etcd_interface: "{{ ansible_default_ipv4.interface }}"
etcd_peers_group: etcd
etcd_client_port: 2379
kube_master: master
kube_master_port: 8080
nodes_group: node
